### ISSUE TITLE
Target hosts via docker connection

### ISSUE THREAD

**Issue by retr0h** [philpep/testinfra#120]
We use ansible to provision our systems.  Some of those systems are bare metal, others are vagrant vms, and others are docker containers.

### Ansible Connection

We currently test our baremetal and vagrant VMs via the ansible connection.  Tests run against all hosts unless the test contains a `testinfra_hosts` list.  This list can contain hostnames or ansible groups.  We happen to target the [ansible group](https://github.com/metacloud/molecule/blob/master/tests/functional/vagrant/scenarios/full/tests/test_example-group1.py).

The command executed is:

` $ testinfra tests/ --connection=ansible --ansible-inventory=.molecule/ansible_inventory`

### Docker Connection

We use the docker connection, and pass all of the hosts on the command line.  So tests which should run on host1 run across host1 and host2.  We cannot leave `--hosts` off in lieu of `--ansible-inventory`.  Since Ansible 2.x supports a docker connection, could we not use the ansible backend so long as `--ansible-inventory` is specifying the connection as `docker`?

The command executed is:

`$ testinfra tests/ --connection=docker --hosts=full-01,full-02'`

### Reproduce

Checkout [our repo](https://github.com/metacloud/molecule)

```
$ pip install molecule
$ cd tests/functional/docker/scenarios/full
# Remove the `pytestmark` mark from the tests `tests/functional/docker/scenarios/full/tests/test_example*.py`
$ molecule test # docker must be installed
```

**Comment by philpep** [comment]
Yes, when `--hosts` is submitted, `testinfra_hosts` is just ignored, and I not sure we want to change this behavior.

When using ansible backend without specifing `--hosts` or `testinfra_hosts`, host are expanded from the inventory (or `all` if nothing provided), that's why it work for you. Keep using ansible backend will workaround this issue.

Since docker backend has no `inventory` notion, hosts list must be specified. You could ensure to have a `testinfra_hosts` in all your tests files for instance.

Related issue #48 to implement easily `skipIf` functionality based on current testinfra host list.

Also note that testinfra has [an API to handle ansible inventories](https://github.com/philpep/testinfra/blob/master/testinfra/utils/ansible_runner.py) that you could use in your tests using the docker backend (as long as you have access to an ansible inventory where inventory name is the related docker host name):

```python
from testinfra.utils.ansible_runner import AnsibleRunner

testinfra_hosts = AnsibleRunner("/path/to/inventory").get_hosts("mygroup")
```

**Comment by retr0h** [comment]
Ok, got it.  I thought I had tried removing `--host` and replacing with name of container via `testinfra_hosts`.

The solutions you describe work as expected.

Thank you as always @philpep
