### ISSUE TITLE
RFC enhanced readability of testinfra fixtures

### ISSUE THREAD

**Issue by philpep** [philpep/testinfra#151]
This is a proposal of a future syntax to replace current fixture system:

```python
# capitalized fixture name that must be repeated for each test declaration
def test_something(Command, Service, Sudo, File, Package):
    [...]
```

Proposition 1: Just one fixture to access all modules and remove capitalization of first letter (could be named Server or Testinfra or Connection or Backend)

```python
def test_something(Server):
    assert Server.service("nginx").is_running
    assert Server.package("nginx").version = "1.4.3"
```

Proposition 2: Import

```python
import pytest
from testinfra.modules import Service

# on whole module or for each testinfra test
pytestmark = pytest.mark.testinfra

def test_something():
    assert Service("nginx").is_running
```

Migration path: DeprecationWarning for v1, drop old usage in v2

**Comment by tinproject** [comment]
I really like the proposition 1, having one only entry point could low the entry barrier for testinfra (only one thing to remember) and I think it's better for auto-complete tools to show what are all the available possibilities.

But, the name `Server` could be misleading because you also could test containers, I would use something more meaningful and explicit to name that 'superfixture', like: `testinfra_subject`, or `testinfra_sut` (sut == subject under test), or something like that, perhaps more succinct. 

Also the capitalization breaks PEP8, its a nuisance that the linter is always yelling about that function arguments must be lowercase, and also punch the principle of least astonishment:
- In the current assert case `assert Service("nginx").is_running`, you think that you are invoking a class, obtaining an instance for the nginx service and then assert a property of that instance, that's ok.
- On the proposition 1 case: `assert Server.service("nginx").is_running`, what do you could think? that you are calling an staticmethod ot a classmethod of the server class? and then, what do you obtain? a Server instance or a Service instance?... that's confusing.

To increase the readability the first I would do is to drop the capitalized names of fixtures.

**Comment by tinproject** [comment]
Another advantage of proposition 1 is that have a whole server fixture could enable to end up testing more than one server in a single file. It has to be a way to define different fixtures for different servers, but this approach goes more in line with the philosophy of pytest and fixture/test composition.

**Comment by philpep** [comment]
Thank you for your advice @tinproject 

I prefer proposition 1 too. About the name of the fixture, what about just ``testinfra`` ? This will clash with a potential ``import testinfra`` statement but it's explicit and clear that the fixture expose testinfra features.

Agree too to keep capitalized name for module who behave like classes, but some of them behave like function or objects (sudo, sysctl, systeminfo).

**Comment by philpep** [comment]
What about naming it ``ti`` (short version of testinfra)

This would be equivalent to:

```
@pytest.fixture()
def ti(TestinfraBackend):
    return TestinfraBackend

def test_foo(ti):
    assert ti.Package(...)
    assert ti.Service(...)
    assert ti.Command.check_output(...)
```

**Comment by andrewschoen** [comment]
Of the two I'd prefer proposition 1, and I'm strongly in favor or removing the capitalization of the fixtures. I'm not sure I see a ton of value in combining all fixtures into one "parent" fixture though. If only because I like to be explicit with the fixtures I'm using.

How would doing that effect the ability to create your own modules by extending existing ones? Would you have to always extend this "parent" testinfra fixture?

**Comment by philpep** [comment]
I think I'm ok to remove capitalization as it make the api confusing.

Also merging the Command module inside the backend would be nice eg: ``ti.check_output(...)`` instead of ``ti.command.check_output(...)``

**Comment by andrewschoen** [comment]
@philpep as an alternative to ``ti``, ``host`` could be used. Essentially we are creating parameters that represent each host given to testinfra.

**Comment by philpep** [comment]
@andrewschoen I'll go for ``host``. Thanks for the suggestion !
