### ISSUE TITLE
Ability to execute testinfra locally

### ISSUE THREAD

**Issue by retr0h** [philpep/testinfra#202]
I'm thinking about writing a testinfra ansible module.  This would allow tests to be written inside the playbook or tasks.   This is particularly useful when wanting to test something has happened but don't want to wait for the playbook to finish converging and verify at the end (such as the molecule workflow).

It looks as though the local driver could be leveraged.  I haven't done a lot of investigation yet, but is it possible?  Have you thought of this use case?

**Comment by retr0h** [comment]
ping

**Comment by philpep** [comment]
Yes I think this could be possible and useful, all testinfra modules are available through a single object `host` that is returned by `testinfra.get_host()`.

There is a similar attempt for salt (asserting with testinfra within the yaml sls file): https://github.com/saltstack/salt/blob/develop/salt/modules/testinframod.py

I guess the simplest way  is to have testinfra installed on target host since ansible modules are copied and executed on the target and use `testinfra.get_host("local://")`.
For remote usage, maybe executing the module with `local_action` and use `testinfra.get_host("ansible://$current_host?ansible_inventory=$current_inventory")`,

**Comment by retr0h** [comment]
Is there a documented python API vs CLI?
