### ISSUE TITLE
DebianPackage `version` method always fails when package is not installed

### ISSUE THREAD

**Issue by codylane** [philpep/testinfra#325]
Hello,

I apologize for not attaching this to #321 but this method inside of `DebianPackage` also looks like it suffers from the same problem as `is_installed` did.  If the package is not installed this will fail every time with an `AssertionError`.

https://github.com/philpep/testinfra/blob/b47c3b181dc445e4661876e909050cc4394b93b1/testinfra/modules/package.py#L99-L104

I wonder if we can apply similar fix for `is_installed` to `version`?  

```
    @property
    def version(self):
        result = self.run_test("dpkg-query -f '${Status} ${Version}' -W %s" % (self.name))
        assert result.rc == 0, 'The package "%s" is not installed'.format(self.name)
        out = result.stdout.strip().split()    
        if out[0].lower() in ["install", "hold"]:
            return out[3]

        # If we get here then None is returned, should we raise an error?  I feel like we should raise an error that the version cannot be determined.
```

**Comment by philpep** [comment]
Hi, thanks for reporting!

I think this isn't a bug since this already fail with an assertion error that say `unexpected return code 3 while running dpkg-query` with stderr of dpkg-query displayed as `dpkg-query: no packages found matching ...`.

However in some cases (I guess for packages that where installed but then uninstalled), `dpkg-query` can exit with a return code 0 and `unknown ok not-installed` as stdout, so I this case we return `None` and I also think we should raise instead.
