### ISSUE TITLE
how to import class and give arguments?

### ISSUE THREAD

**Issue by michaelhajjar** [philpep/testinfra#331]
Hello,

I have a question. I have created a class with some tests.
I would like to add the class to a CLI tool we are creating (in the cement framework) and add arguments to it.
How can I add arguments in the class since the __init__ costructor is not working?
is is for the backend configuration (paramiko with a username arg, server arg and private_key arg).

here is the test:

```
import testinfra
import pytest


class TestTemp(object):

    # establish connection to server
    connect = testinfra.get_host("paramiko://usernamearg@serverarg", ssh_identity_file=private_keyarg)


    # test if packages are installed, before template creation
    def test_pkg_installed(self):
        # define packages that need to be checked
        packages = ["cloud-init", "open-vm-tools", "perl"]

        for pkg in packages:
            assert self.connect.package(pkg).is_installed


    # test if service is enabled
    def test_service_enabled(self):
        # define services that need to be checked
        packages = ["vmtoolsd", "cloud-init", "sshd"]

        for pkg in packages:
            service = self.connect.service(pkg)
            assert service.is_enabled


    # test if service is enabled
    def test_service_running(self):
        # define services that need to be running
        packages = ["vmtoolsd"]

        for pkg in packages:
            service = self.connect.service(pkg)
            assert service.is_running


    # test if repo exists
    def test_repo_exists(self):
        # define repos that need to be checked
        repos = ["repo_os", "repo_updates", "repo_saltstack",
                 "repo_epel", "repo_duo", "repo_cloud_init",
                 "repo_extras", "repo_ansible"]

        for repo in repos:
            repo_path = "/etc/yum.repos.d/" + repo + ".repo"
            h_file = self.connect.file
            assert h_file(repo_path).exists


    def test_yum_update(self):
        assert self.connect.check_output("yum check-update")


def run_tests():
  pytest.main(['-v', '--disable-warnings', '-r', 'P'])

```

**Comment by philpep** [comment]
Hello, I think your TestTemp should inherit from `unittest.TestCase`.

**Comment by codylane** [comment]
I'm not sure how your CLI thingy is supposed to work and how it's related to this problem, but I will attempt to answer your Class based test question.

testinfra use `pytest` and in it's self is a pytest plugin.  I like pytest, but it took me a while to understand how fixtures work.  Fixtures, are the things that testinfra provides in order to make our lives easier as  testers.  There is nothing really wrong with what you are asking or doing but think there might be some confusion how testinfra works with your tests.  

Take this for example
```
import testinfra
import pytest


class TestTemp(object):

    # establish connection to server
    connect = testinfra.get_host("paramiko://usernamearg@serverarg", ssh_identity_file=private_keyarg)


    # test if packages are installed, before template creation
    def test_pkg_installed(self):
        # define packages that need to be checked
        packages = ["cloud-init", "open-vm-tools", "perl"]

        for pkg in packages:
            assert self.connect.package(pkg).is_installed
```

There is nothing wrong with that, but that is not really the correct way to use testinfra or pytest.  In fact, I think I understand why you are doing it that way, but I'm going to try and steer you down the path that `pytest` testers use and encourage you to use fixtures as decroators or inside your test methods. Try to avoid wrapping test arguments into global variable(s) or you will have surprises and potential race conditions especially if you plan to use `xdist` and parallelize your tests.  Avoid that hassle!

Instead I would like to encourage you to try this for your Class based tests **DISCLAIMER** I have not tested this, this will left for you but it should highlight the documented way of using [pytest fixtures](https://docs.pytest.org/en/latest/fixture.html#fixtures-as-function-arguments) and [testinfra](https://testinfra.readthedocs.io/en/latest/examples.html)

```
import os
import testinfra
import pytest

SSH_PRIV_KEY = os.environ.get('PARAMIKO_SSH_PRIVATE_KEY', '~/.ssh/id_rsa')
PARAMIKO_CONNECT = (
    "paramiko://usernamearg@serverarg", 
    ssh_identity_file=SSH_PRIV_KEY
)

class TestTemp(object):

    # "host" is a pytest test fixture
    @pytest.mark.testinfra_hosts(*PARAMIKO_CONNECT)
    def test_pkg_installed(self, host):
        # define packages that need to be checked
        packages = ["cloud-init", "open-vm-tools", "perl"]

        for pkg in packages:
            assert host.package(pkg).is_installed

    @pytest.mark.testinfra_hosts(*PARAMIKO_CONNECT)
    def test_foobar(self, host):
        assert False, 'need to implement this'
```

The above is not only more explicit of what, you are testing for, but also where.  No magic!  I strongly encourage no magic when you are testing, duplicate tests if you have too, don't go overboard with variables and configuration of tests, it will bite you down the road and you never want to be in the boat *"Hey, my tests are complicated and I don't know how they work anymore."* 

Small, concise, terse testing is the key to better testing.  Also, the above example has the added benefits of what makes `pytest` so freaking awesome.  When used in the `decorator` form above you also take advance of automatic `setup` and `teardown` routines to fire depending on how you `scope` your tests.  See the `pytest` docs for examples on scoping. 

Anyway, I hope this helped.

**Comment by michaelhajjar** [comment]
@philpep, @codylane thank you very much, I have found a solution with your help.
