### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ryancurrah** [philpep/testinfra#39]
Hello I recently tried to use testinfra on Windows it did work. Would you be open to pull request to support windows? And if so are open do you have any opinions on what i would need to do to start? I have a decent python background and another developer willing to help.

**Comment by daenney** [comment]
I don't see any reason not to accept Windows support, if anything that'll be tremendously helpful to people and I doubt @philpep would object.

The place to start is look at how the current code base is structured and implement the Windows backends for it. Probably also set up something with AppVeyor so we can actually test the windows components.

**Comment by philpep** [comment]
Hello,

Indeed I'm not opposed about a windows support. But I cannot maintain it myself because I don't work with windows. So I'm must be sure that someone (you ?) will maintain it, that suppose a commitment.

The best option I see for now is to work on a separate project that extend testinfra (basically this will be a pytest plugin). See https://testinfra.readthedocs.org/en/latest/examples.html#make-your-own-modules

But before doing this, we must implement an API to extend testinfra backends #10 and to extend existing modules (eg. File).

**Comment by ingrittota** [comment]
Hello @ryancurrah 

I am interested in using testinfra on Windows, as well! Do you have the code posted anywhere as of now?

**Comment by williamsia** [comment]
Hi, is someone still interested in this? we can follow the example of SpecInfra https://github.com/mizzy/specinfra , connecting through winrm and using powershell to check things. In python we can use either pywinrm or winrm lib to do this.

**Comment by ryancurrah** [comment]
No I have not worked on this probably should close it.

**Comment by williamsia** [comment]
@ryancurrah , if you're interested https://github.com/MagenTys/testinfra I extend the testinfra to uses winrm to test windows machine. I am using the similar approach used by Ansible and ServerSpec.

**Comment by mkinney** [comment]
Since this is a closed issue, I suspect that no one will respond to it. 

@williamsia Would you be willing to open a new issue and perhaps create a PR for this.

**Comment by mkinney** [comment]
Nevermind. Looks like there is a winrm backend now.
