### ISSUE TITLE
setuptools_scm.version.SetuptoolsOutdatedWarning: your setuptools is too old

### ISSUE THREAD

**Issue by decentral1se** [philpep/testinfra#417]
Hi there! 

We've seen the following reported in Molecule (over in https://github.com/ansible/molecule/issues/1859#issue-423669576):

```
$ pip install --user molecule
[...]
Collecting testinfra==1.19.0 (from molecule==2.20)
  Using cached https://files.pythonhosted.org/packages/2b/96/3c0eb74894acf3e026e437ee1b1161a200adb9c9a189c36bc4a92ed2db79/testinfra-1.19.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-asndpD/testinfra/setup.py", line 59, in <module>
        'six>=1.4',
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 302, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-asndpD/testinfra/setuptools_scm-3.2.0-py2.7.egg/setuptools_scm/integration.py", line 10, in version_keyword
      File "/tmp/pip-build-asndpD/testinfra/setuptools_scm-3.2.0-py2.7.egg/setuptools_scm/version.py", line 66, in _warn_if_setuptools_outdated
    setuptools_scm.version.SetuptoolsOutdatedWarning: your setuptools is too old (<12)
```

The comment in https://github.com/ansible/molecule/issues/1859#issuecomment-475332782 (slightly irate but well meaning, hope you understand :)) that argued for a fix over here in `testinfra`. It hinted at a solution where we could avoid `setuptools` being involved in the install process completely (I defer to @webknjaz at what that solution looks like).

If we're coming to an agreement, I have some time to commit for the fix.

Thanks for the good work here.

**Comment by ssbarnea** [comment]
Cannot this be avoided by adding a minimal version of setuptools at https://github.com/philpep/testinfra/blob/master/setup.py#L52 ?

**Comment by webknjaz** [comment]
No, setuptools can't depend on itself. Even if you install it, old version is already imported in the runtime. You should use `pyproject.toml` and also just provide proper wheels

**Comment by philpep** [comment]
> @decentral1se I'd argue that we should go to testinfra upstream and tell them how to do their job make/ask/help them package proper wheels in which case setuptools wouldn't be involved at all.
> I'm starting to think that we need to gather and organize a "Crusade" across our dependencies and tell them all to package things properly, probably providing help with that. It seems a bit better (easier?) than tutoring end-users about specifics of Python packaging...
> I mean, I'm already doing this selectively sometimes. For example, I've got lxc lib on my list for implementing proper packaging for them... If someone is up to doing this, I'm willing to be consulting them should they need any help with doing modern packaging, because I myself don't have much time, unfortunately.

Hi, @webknjaz

Is this a joke ? Because it's actually very funny :D

Centos 7 packaged setuptools version is 0.9.8 and was released in 2013, 6 years ago, yes..., and is largely unmaintained, probably like every python package in Centos. Since you seems to be paid by RedHat, may I suggest to do your job and provide maintained, working and secure packages to your users ?  And you're arguing about "package things properly" and "doing modern packaging", LOL.

You used the word "Crusade", this is quite revealer here...

FYI, I never get paid for developing and maintaining testinfra. There's three topics where I and contributors have spent a lot of time and annoyance: ansible (due to it's lack of proper python API), Centos 6 (for the former reasons) and Windows support (obvious).

You seems to be a ansible core dev, so maybe I can ask you to do your job and provide a working python API that I'm waiting for 4 years ? Hopefully there's ongoing work https://github.com/philpep/testinfra/pull/410

I'd suggest to ask your company to pay me or someone to maintain support for ansible and Centos in testinfra.

About this particular issue, providing wheels to pypi should workaround your lack of modern packaging and sounds reasonable to me. BTW I'm very impressed that Centos 7 python-pip package support installing wheels :D

FYI I'm planning to drop python 2 and 3.4 support when pytest 5 will be released, following schedule in https://docs.pytest.org/en/latest/py27-py34-deprecation.html . Will Centos 7 be ready for this ? Do you have a package for python3 ? :D

Cheers,

**Comment by ssbarnea** [comment]
When read this thread few hours ago I was ready to reply right away but I am glad I didn't because I was bit "negatively loaded".

I invite everyone involved in this to take break, let this rest a bit and look again in a couple of days and try to find common grounds, solutions.

Most of us do open-source contributions in our free time, regardless who is employing us. Lets thing about ways of doing things that do not break others workflows. Or at least when this happens by mistake, lets work togheter in finding solutions.

**Comment by webknjaz** [comment]
@philpep it looks you have very unexpected views of what my job is and probably no understanding of what it feels like to try coping with quite a high-volume projects. I offered my help. If you don't need it, it doesn't mean that you should be mean to everyone around.
P.S. I have no idea about centos so have nothing to tell you but please be respectful. Insulting people is not cool.
P.P.S. Sorin is right if we _only_ did our jobs you'd not see any contributions around. We do much more and being thankless is far from being motivating.

**Comment by decentral1se** [comment]
Quietly sneaks out the back door ...

**Comment by philpep** [comment]
... creaking door ...

I uploaded wheels for testinfra 2.0.0 and 1.19.0 (the version pinned by molecule), which should fix installation of molecule/testinfra bypassing systems shipping old setuptools.

*slam*

**Comment by ssbarnea** [comment]
Thanks @philpep, i really appreciate! Extra kudos for the best update message I read so far, really multimedia.
