### ISSUE TITLE
Testinfra 3.x get_variables does not work

### ISSUE THREAD

**Issue by retr0h** [philpep/testinfra#447]
When using ansible 2.8 and testinfra 3.0.4 we cannot get variables.  The same problem occurs with Ansible 2.7 when using testinfra 3.0.4.

However, this works under ansible 2.7 and testinfra 2.1.0.  Looks like 3.x broke the `get_variables` functionality.

```
host.ansible('setup')
ansible_vars = host.ansible.get_variables()
ansible_vars['ansible_os_family']
```

```
    E       KeyError: 'ansible_os_family'
```

```
[jodewey:~/git/ansible-role-chrony]   : issue-3(+2/-3)+ ± pip freeze | egrep 'testinfra|ansible'
ansible==2.8.0
testinfra==3.0.4
```

**Comment by philpep** [comment]
Hi,

I didn't know about this side effect feature :) In testinfra 2.X we used ansible API directly and looks calling `setup` filled some variables cache returned by `get_variables()`. This doens't work in testinfra 3.X because we now call ansible in a subprocess.
I'm not sure we want to provide backward compatibility for this because this was a kind of magic side effect of calling `setup`.

You can write equivalent code with:

```python
host.ansible('setup')['ansible_facts']['ansible_os_family']
```

**Comment by retr0h** [comment]
Works like a [charm](https://github.com/ericsysmin/ansible-role-chrony/pull/4).

Thanks @philpep 🤘
