### ISSUE TITLE
How to set connection timeout?

### ISSUE THREAD

**Issue by krepflap** [philpep/testinfra#449]
I'm using `--hosts=all --ansible-inventory=inventory --connection ansible` where `inventory` is a file containing an Ansible inventory.

However if there is a host unreachable (e.g. down or blocked by firewall), the tests take forever.

How can we set the timeout to be shorter?

To reproduce, just add something like `google.com` or so to your inventory file. I'm dealing with automated inventories and sometimes the host are just down, I'm looking for a way for them not to make the whole testrun slow.

**Comment by philpep** [comment]
Hi, thanks for reporting !

Indeed since testinfra 3.X we use our own ssh (paramiko) connection to connect ansible hosts, and we doesn't have a timeout set, whereas ansible have a default timeout set to 10 seconds.

This should be fixed by https://github.com/philpep/testinfra/pull/450/commits/ed611a0efc80bc4a6d29218de55b132abd1e8343 which will be released ASAP.

**Comment by krepflap** [comment]
@philpep : Awesome, thanks.

A default setting certainly helps, perhaps in the future we could also overwrite this with ConnectTImeout via the custom ssh_config ?

Also, I had an additional question, I'm not too familiar with pytest, but do you know of a way to first test the connectivity of the host and then, if the host is unreachable skip the rest of the tests?

E.g. I have 20 tests defined, currently for each test testinfra will try to connect (via paramiko) 20 times, each time waiting for the timeout when a host is unreachable, maybe there's a pattern you know of that I can use to avoid this?

Thanks!
